name       : pygments
version    : 2.3.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz : 5ffada19f6203563680669ee7f53b64dabbeb100eb51b61996085e99c03b284a
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python.
description: |
    Pygments is a syntax highlighting package written in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
