name       : pygments
version    : 2.12.0
release    : 13
source     :
    - https://pypi.io/packages/source/P/Pygments/Pygments-2.12.0.tar.gz : 5eb116118f9612ff1ee89ac96437bb6b49e8f04d8a13b514ba26f620208e26eb
homepage   : https://pygments.org/
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python
description: |
    t is a generic syntax highlighter written in Python that supports over 500 languages and text formats, for use in code hosting, forums, wikis or other applications that need to prettify source code.
build      : |
    %python3_setup
install    : |
    %python3_install
