name       : pygments
version    : 2.5.2
release    : 9
source     :
    - https://files.pythonhosted.org/packages/cb/9f/27d4844ac5bf158a33900dbad7985951e2910397998e85712da03ce125f0/Pygments-2.5.2.tar.gz : 98c8aa5a9f778fcd1026a17361ddaf7330d1b7c62ae97c3bb0ae73e0b9b6b0fe
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python.
description: |
    Pygments is a syntax highlighting package written in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
