name       : pygments
version    : 2.1.3
release    : 1
source     :
    - https://pypi.python.org/packages/b8/67/ab177979be1c81bc99c8d0592ef22d547e70bb4c6815c383286ed5dec504/Pygments-2.1.3.tar.gz : 88e4c8a91b2af5962bfa5ea2447ec6dd357018e86e94c7d14bd8cacbc5b55d81
license    : BSD
component  : programming
summary    : Pygments is a syntax highlighting package written in Python.
description: |
    Pygments is a syntax highlighting package written in Python.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
