name       : pygments
version    : 2.8.0
release    : 10
source     :
    - https://pypi.io/packages/source/P/Pygments/Pygments-2.8.0.tar.gz : 37a13ba168a02ac54cc5891a42b1caec333e59b66addb7fa633ea8a6d73445c0
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python.
description: |
    Pygments is a syntax highlighting package written in Python.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
