name       : pygments
version    : 2.2.0
release    : 3
source     :
    - https://pypi.python.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz : dbae1046def0efb574852fab9e90209b23f556367b5a320c0bcb871c77c3e8cc
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python.
description: |
    Pygments is a syntax highlighting package written in Python.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
