name       : pygments
version    : 2.14.0
release    : 16
source     :
    - https://pypi.io/packages/source/P/Pygments/Pygments-2.14.0.tar.gz : b3ed06a9e8ac9a9aae5a6f5dbe78a8a58655d17b43b93c078f094ddc476ae297
homepage   : https://pygments.org/
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python
description: |
    Pygments is a generic syntax highlighter written in Python that supports over 500 languages and text formats, for use in code hosting, forums, wikis or other applications that need to prettify source code.
build      : |
    %python3_setup
install    : |
    %python3_install
